name: Lint CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      - name: Install bundle
        run: |
          gem install bundler -v "2.3.18"
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Lint
        run: ./gradlew --stacktrace :app:ktlintCheck detektCheck
      - name: Run Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
